services:
  codenest.api:
    image: ${DOCKER_REGISTRY-}codenestapi
    build:
      context: .
      dockerfile: CodeNest.Api/Dockerfile
    ports:
      - 5000:8000
      - 5001:8081 
    environment:
      #SEQ
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://codenest.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf   
# Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://codenest.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/grpc

  codenest.seq:
    image: datalust/seq:2024.3
    environment:
        ACCEPT_EULA: "Y"
    volumes:
        - ./.containers/sqe_data:/data
    ports:
        - 8080:80
        - 5341:5341
   
  codenest.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYNOUS: true
    ports:
      - 18888:18888

